import type { Product } from "@/types";

export const products: Product[] = [
  {
    id: "1",
    slug: "smart-watch-series-5-silver",
    title: "Smart Watch Series 5 - Silver",
    category: "Mobile accessory",
    brand: "Apple",
    features: ["Metallic", "GPS", "Fitness"],
    condition: "new",
    verified: true,
    image: "/images/products/Smartwatch.png",
    images: ["/images/products/Smartwatch.png", "/images/products/Smartwatch.png", "/images/products/Smartwatch.png"],
    price: 99.5,
    originalPrice: 128,
    rating: 4.2,
    reviewCount: 32,
    orders: 154,
    sold: 154,
    freeShipping: true,
    shortDescription: "Advanced fitness smartwatch with GPS and heart-rate tracking.",
    description: "A dependable everyday smartwatch with multi-day battery life, workout tracking, GPS, and durable aluminum construction.",
    specs: { Model: "SW-5S-2024", Style: "Modern Sport", Certificate: "CE, FCC", Size: "44mm case", Memory: "32GB Storage" },
  },
  {
    id: "2",
    slug: "iphone-13-pro-max-blue",
    title: "iPhone 13 Pro Max - Blue",
    category: "Smartphones",
    brand: "Apple",
    features: ["Large Memory", "Metallic", "5G"],
    condition: "new",
    verified: true,
    image: "/images/products/blue_iphone.png",
    images: ["/images/products/blue_iphone.png", "/images/products/blue_iphone.png", "/images/products/blue_iphone.png"],
    price: 899,
    originalPrice: 999,
    rating: 4.8,
    reviewCount: 432,
    orders: 432,
    sold: 892,
    freeShipping: true,
    shortDescription: "Flagship iPhone with a large display and pro camera system.",
    description: "A premium smartphone with smooth performance, vibrant display, long battery life, and excellent cameras for everyday creators.",
    specs: { Model: "A2643", Style: "Premium", Certificate: "Apple Certified", Size: "160.8 x 78.1 x 7.65 mm", Memory: "256GB" },
  },
  {
    id: "3",
    slug: "gopro-hero10-4k-action-camera",
    title: "GoPro HERO10 4K Action Camera",
    category: "Electronics",
    brand: "GoPro",
    features: ["Super power", "Waterproof", "4K"],
    condition: "new",
    verified: true,
    image: "/images/products/Gorpro.png",
    images: ["/images/products/Gorpro.png", "/images/products/Gorpro.png", "/images/products/Gorpro.png"],
    price: 349.99,
    originalPrice: 399.99,
    rating: 4.5,
    reviewCount: 210,
    orders: 210,
    sold: 456,
    freeShipping: true,
    shortDescription: "Compact action camera for travel, sports, and outdoor capture.",
    description: "Capture stabilized high-resolution video and crisp photos in a lightweight waterproof action camera built for adventure.",
    specs: { Model: "CHDHX-101", Style: "Action Cam", Certificate: "IP68", Size: "71 x 55 x 33.6 mm", Memory: "SD Card up to 1TB" },
  },
  {
    id: "4",
    slug: "sony-wireless-headphones",
    title: "Sony Wireless Headphones",
    category: "Electronics",
    brand: "Sony",
    features: ["Large Memory", "Bluetooth", "Noise Canceling"],
    condition: "new",
    verified: false,
    image: "/images/products/headphones.png",
    images: ["/images/products/headphones.png", "/images/products/headphones.png"],
    price: 149,
    originalPrice: 199,
    rating: 4.1,
    reviewCount: 102,
    orders: 198,
    sold: 198,
    freeShipping: true,
    shortDescription: "Wireless over-ear headphones with strong battery life.",
    description: "Comfortable wireless headphones with balanced sound, soft earcups, and reliable everyday battery performance.",
    specs: { Model: "WH-XB910N", Style: "Over-ear", Certificate: "CE", Size: "One size", Memory: "N/A" },
  },
  {
    id: "5",
    slug: "macbook-pro-m2-space-gray",
    title: "MacBook Pro M2 - Space Gray",
    category: "Modern tech",
    brand: "Apple",
    features: ["Large Memory", "8GB Ram", "Metallic"],
    condition: "new",
    verified: true,
    image: "/images/products/Laptop.png",
    images: ["/images/products/Laptop.png", "/images/products/Laptop.png"],
    price: 1299,
    originalPrice: 1499,
    rating: 4.9,
    reviewCount: 89,
    orders: 89,
    sold: 89,
    freeShipping: false,
    shortDescription: "High-performance laptop for work, editing, and travel.",
    description: "A lightweight premium laptop with strong battery life, excellent screen quality, and fast day-to-day performance.",
    specs: { Model: "MNEH3", Style: "Pro", Certificate: "Energy Star", Size: "13-inch", Memory: "8GB RAM / 512GB SSD" },
  },
  {
    id: "6",
    slug: "iphone-14-pro-deep-purple",
    title: "iPhone 14 Pro - Deep Purple",
    category: "Smartphones",
    brand: "Apple",
    features: ["Large Memory", "5G", "Metallic"],
    condition: "refurbished",
    verified: true,
    image: "/images/products/red_iphone.png",
    images: ["/images/products/red_iphone.png", "/images/products/red_iphone.png"],
    price: 999,
    originalPrice: 1099,
    rating: 4.7,
    reviewCount: 267,
    orders: 267,
    sold: 267,
    freeShipping: true,
    shortDescription: "A premium refurbished iPhone with flagship performance.",
    description: "Professionally refurbished flagship smartphone with excellent camera quality, bright display, and premium build.",
    specs: { Model: "A2890", Style: "Premium", Certificate: "Refurbished Grade A", Size: "6.1-inch", Memory: "256GB" },
  },
  {
    id: "7",
    slug: "mens-casual-t-shirt-blue",
    title: "Men's Casual T-Shirt Blue",
    category: "Clothes and wear",
    brand: "Pocco",
    features: ["Plastic cover", "Breathable", "Everyday"],
    condition: "new",
    verified: false,
    image: "/images/products/bluetshirt.png",
    images: ["/images/products/bluetshirt.png"],
    price: 24.99,
    originalPrice: 35,
    rating: 3.9,
    reviewCount: 87,
    orders: 543,
    sold: 543,
    freeShipping: false,
    shortDescription: "Soft casual tee for daily wear.",
    description: "A lightweight, comfortable t-shirt designed for everyday wear with a relaxed fit and durable stitching.",
    specs: { Model: "TS-BLU-01", Style: "Casual", Certificate: "OEKO-TEX", Size: "M / L / XL", Memory: "N/A" },
  },
  {
    id: "8",
    slug: "winter-coat-premium-black",
    title: "Winter Coat Premium - Black",
    category: "Clothes and wear",
    brand: "Lenovo",
    features: ["Super power", "Warm", "Metallic"],
    condition: "new",
    verified: true,
    image: "/images/products/coat.png",
    images: ["/images/products/coat.png"],
    price: 149.5,
    originalPrice: 199,
    rating: 4.3,
    reviewCount: 124,
    orders: 124,
    sold: 124,
    freeShipping: true,
    shortDescription: "Heavyweight winter coat with a clean silhouette.",
    description: "A premium insulated coat with a structured fit, practical pockets, and dependable cold-weather warmth.",
    specs: { Model: "CT-BLK-03", Style: "Outerwear", Certificate: "ISO-Textile", Size: "S / M / L", Memory: "N/A" },
  },
  {
    id: "9",
    slug: "travel-backpack",
    title: "Travel Backpack",
    category: "Mobile accessory",
    brand: "Samsung",
    features: ["Large Memory", "Travel", "Water-resistant"],
    condition: "new",
    verified: false,
    image: "/images/products/backpack.png",
    images: ["/images/products/backpack.png"],
    price: 99,
    originalPrice: 129,
    rating: 4,
    reviewCount: 63,
    orders: 143,
    sold: 143,
    freeShipping: false,
    shortDescription: "Organized backpack for commuting and travel.",
    description: "A structured backpack with multiple compartments, travel-friendly capacity, and durable fabric.",
    specs: { Model: "BP-TR-02", Style: "Travel", Certificate: "CE", Size: "30L", Memory: "N/A" },
  },
  {
    id: "10",
    slug: "leather-wallet",
    title: "Leather Wallet",
    category: "Mobile accessory",
    brand: "Huawei",
    features: ["Metallic", "Compact"],
    condition: "new",
    verified: true,
    image: "/images/products/wallet.png",
    images: ["/images/products/wallet.png"],
    price: 34,
    originalPrice: 42,
    rating: 4.1,
    reviewCount: 40,
    orders: 88,
    sold: 88,
    freeShipping: true,
    shortDescription: "Compact wallet with premium leather finish.",
    description: "A neat everyday wallet with multiple card slots, a slim profile, and durable stitched leather.",
    specs: { Model: "WL-LTHR", Style: "Classic", Certificate: "N/A", Size: "Bi-fold", Memory: "N/A" },
  },
  {
    id: "11",
    slug: "gaming-headset-white",
    title: "Gaming Headset",
    category: "Electronics",
    brand: "Samsung",
    features: ["8GB Ram", "Surround", "Plastic cover"],
    condition: "new",
    verified: true,
    image: "/images/products/white headset.png",
    images: ["/images/products/white headset.png"],
    price: 89,
    originalPrice: 109,
    rating: 3.8,
    reviewCount: 52,
    orders: 97,
    sold: 97,
    freeShipping: true,
    shortDescription: "Comfortable gaming headset with clear voice pickup.",
    description: "An affordable gaming headset with lightweight build, balanced sound, and an adjustable microphone boom.",
    specs: { Model: "GH-WHT", Style: "Gaming", Certificate: "CE", Size: "Adjustable", Memory: "N/A" },
  },
  {
    id: "12",
    slug: "electric-kettle-black",
    title: "Electric Kettle",
    category: "Home interiors",
    brand: "Pocco",
    features: ["Super power", "Kitchen", "Plastic cover"],
    condition: "new",
    verified: false,
    image: "/images/products/black_cup.png",
    images: ["/images/products/black_cup.png"],
    price: 80.95,
    originalPrice: 90,
    rating: 4,
    reviewCount: 19,
    orders: 36,
    sold: 36,
    freeShipping: false,
    shortDescription: "Fast-boil kettle with compact countertop footprint.",
    description: "A practical electric kettle with easy-pour spout, auto shutoff, and quick heating performance.",
    specs: { Model: "KT-BLK", Style: "Kitchen", Certificate: "CE", Size: "1.7L", Memory: "N/A" },
  },
  {
    id: "13",
    slug: "soft-chair-white",
    title: "Soft Chair",
    category: "Home interiors",
    brand: "Lenovo",
    features: ["Modern", "Comfort"],
    condition: "new",
    verified: true,
    image: "/images/products/white_chair.png",
    images: ["/images/products/white_chair.png"],
    price: 119,
    originalPrice: 149,
    rating: 4.4,
    reviewCount: 18,
    orders: 24,
    sold: 24,
    freeShipping: false,
    shortDescription: "Soft accent chair for living rooms and reading corners.",
    description: "A compact accent chair with supportive cushioning and a modern neutral finish that suits many interiors.",
    specs: { Model: "CHR-WHT", Style: "Modern", Certificate: "ISO-Furniture", Size: "Single seat", Memory: "N/A" },
  },
  {
    id: "14",
    slug: "blender-coffee-machine",
    title: "Coffee Machine Blender",
    category: "Home interiors",
    brand: "Huawei",
    features: ["Kitchen", "Super power"],
    condition: "refurbished",
    verified: true,
    image: "/images/products/whitecoffemachine.png",
    images: ["/images/products/whitecoffemachine.png"],
    price: 240,
    originalPrice: 280,
    rating: 4.1,
    reviewCount: 14,
    orders: 18,
    sold: 18,
    freeShipping: false,
    shortDescription: "Countertop coffee and blending appliance for small kitchens.",
    description: "A refurbished countertop appliance suited for compact kitchens and quick morning beverage prep.",
    specs: { Model: "CM-BLND", Style: "Kitchen", Certificate: "Refurbished Grade A", Size: "Countertop", Memory: "N/A" },
  },
];
